"""add Comment

Revision ID: 000449fa92c9
Revises: a4051517667f
Create Date: 2022-07-22 14:57:27.616092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000449fa92c9'
down_revision = 'a4051517667f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('comment', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'disabled')
    op.drop_column('comment', 'content_html')
    # ### end Alembic commands ###
