"""add markdown

Revision ID: 1c07475a94a9
Revises: aa41bb012ffe
Create Date: 2022-07-21 10:41:39.038997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c07475a94a9'
down_revision = 'aa41bb012ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'article', ['title'], unique=True)
    # ### end Alembic commands ###
