"""empty message

Revision ID: 2ec13cde4adf
Revises: aab117ff67c9
Create Date: 2022-09-01 10:33:17.719499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec13cde4adf'
down_revision = 'aab117ff67c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articleimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imgpath', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articleimage_addtime'), 'articleimage', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articleimage_addtime'), table_name='articleimage')
    op.drop_table('articleimage')
    # ### end Alembic commands ###
