"""add user_login

Revision ID: 47e827ee0a4c
Revises: cb2c5356b59e
Create Date: 2022-05-10 18:20:53.916205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e827ee0a4c'
down_revision = 'cb2c5356b59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_users', sa.Column('pwd', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_users', 'pwd')
    # ### end Alembic commands ###
