"""add tinymce

Revision ID: 4ce8b1ae268e
Revises: bedccab79d4e
Create Date: 2022-07-25 17:52:38.884943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ce8b1ae268e'
down_revision = 'bedccab79d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body_blob', sa.BLOB(), nullable=True))
    op.drop_column('article', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body', mysql.TEXT(), nullable=True))
    op.drop_column('article', 'body_blob')
    # ### end Alembic commands ###
