"""add Tag.source

Revision ID: 4d8fc303d7af
Revises: b013aa08053f
Create Date: 2022-12-15 10:20:23.445633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8fc303d7af'
down_revision = 'b013aa08053f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('source', table_name='tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('source', 'tag', ['source'], unique=False)
    # ### end Alembic commands ###
