"""add Roles

Revision ID: 50097b945236
Revises: 8250c244bf1d
Create Date: 2022-05-13 16:37:03.837414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50097b945236'
down_revision = '8250c244bf1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'auth', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###
