"""empty message

Revision ID: 510db5ec246e
Revises: 9e9ec3cf8b67
Create Date: 2022-10-12 11:00:55.823922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510db5ec246e'
down_revision = '9e9ec3cf8b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('tag_name_en', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'tag', ['tag_name_en'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('tag', 'tag_name_en')
    # ### end Alembic commands ###
