"""add markdown

Revision ID: 7c56f447c68e
Revises: 4b7b42819f9f
Create Date: 2022-07-20 10:04:36.682724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c56f447c68e'
down_revision = '4b7b42819f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'body_html')
    # ### end Alembic commands ###
