"""add tinymce

Revision ID: 804e4ad2f8d1
Revises: 4ce8b1ae268e
Create Date: 2022-07-26 11:11:50.247475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804e4ad2f8d1'
down_revision = '4ce8b1ae268e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body_html', sa.Text(), nullable=True))
    op.drop_column('article', 'body_blob')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body_blob', sa.BLOB(), nullable=True))
    op.drop_column('article', 'body_html')
    # ### end Alembic commands ###
