"""add user_detail

Revision ID: 8089c0629a31
Revises: 50097b945236
Create Date: 2022-05-16 16:57:32.052572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8089c0629a31'
down_revision = '50097b945236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('real_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'real_name')
    op.drop_column('user', 'location')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
