"""add_ArticleImage

Revision ID: 9e9ec3cf8b67
Revises: 2ec13cde4adf
Create Date: 2022-09-01 11:41:52.991111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e9ec3cf8b67'
down_revision = '2ec13cde4adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articleimage', sa.Column('show', sa.Boolean(), nullable=True))
    op.drop_column('articleimage', 'disabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articleimage', sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('articleimage', 'show')
    # ### end Alembic commands ###
