"""add markdown

Revision ID: aa41bb012ffe
Revises: 7c56f447c68e
Create Date: 2022-07-20 10:21:43.429882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa41bb012ffe'
down_revision = '7c56f447c68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'body_html')
    # ### end Alembic commands ###
