"""empty message

Revision ID: b013aa08053f
Revises: 510db5ec246e
Create Date: 2022-12-15 09:55:59.120630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b013aa08053f'
down_revision = '510db5ec246e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('source', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'tag', ['source'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('tag', 'source')
    # ### end Alembic commands ###
