"""add tinymce

Revision ID: bedccab79d4e
Revises: 000449fa92c9
Create Date: 2022-07-25 16:41:59.800751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bedccab79d4e'
down_revision = '000449fa92c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('body_html', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
