"""add auth

Revision ID: de0abbb7bc79
Revises: 8089c0629a31
Create Date: 2022-05-17 15:51:59.815196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0abbb7bc79'
down_revision = '8089c0629a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'admin', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='foreignkey')
    # ### end Alembic commands ###
