"""del admin

Revision ID: fe92b8e0be41
Revises: de0abbb7bc79
Create Date: 2022-05-18 14:46:07.317127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe92b8e0be41'
down_revision = 'de0abbb7bc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_admin_addtime', table_name='admin')
    # op.drop_index('name', table_name='admin')
    # # op.drop_table('admin')
    # op.drop_index('ix_oplog_addtime', table_name='oplog')
    # op.drop_table('oplog')
    # op.drop_index('ix_adminlog_addtime', table_name='adminlog')
    # op.drop_table('adminlog')
    # op.drop_index('ix_auth_addtime', table_name='auth')
    # op.drop_index('name', table_name='auth')
    # op.drop_index('url', table_name='auth')
    # op.drop_table('auth')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('url', 'auth', ['url'], unique=True)
    op.create_index('name', 'auth', ['name'], unique=True)
    op.create_index('ix_auth_addtime', 'auth', ['addtime'], unique=False)
    op.create_table('adminlog',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name='adminlog_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_adminlog_addtime', 'adminlog', ['addtime'], unique=False)
    op.create_table('oplog',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('reason', mysql.VARCHAR(length=600), nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name='oplog_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_oplog_addtime', 'oplog', ['addtime'], unique=False)
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('pwd', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_super', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='admin_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'admin', ['name'], unique=True)
    op.create_index('ix_admin_addtime', 'admin', ['addtime'], unique=False)
    # ### end Alembic commands ###
